### ISSUE TITLE
Throws an error before the Menu Screen

### ISSUE THREAD

**Issue by Sylladexter** [justinhschaaf/LlamaSteeds#2]
This message appears before the Menu Screen. I don't know if this is enough information. Let me know if you need more.
![image](https://user-images.githubusercontent.com/37201783/110250605-216c8680-7f4a-11eb-9003-307769f3cf0d.png)

EDIT: I don't make mods and maybe I'm wrong but on the forge documentation the  `versionRange` property seems to end with a "]" and not ",)"

https://github.com/justinhschaaf/LlamaSteeds/blob/c175ae75fdc121024daf09acd13180504aca254a/src/main/resources/META-INF/mods.toml#L51

**Comment by justinhschaaf** [comment]
This should be fixed with Release 2021.03.08. The issue was simply that I didn't include a pack.mcmeta (because I didn't have any resources to include), since Forge apparently checks for it and throws a warning if it's not present. 

The update is available currently on the GitHub Releases page, or on CurseForge in about a day (that's usually how long it takes to get a file approved). The warning can also be dismissed for the time being with no problems using the "Proceed to main menu" button at the bottom of the screen.

On the `versionRange="[1.16.1,)"`, you'd be correct in that it would usually end in a bracket, but I wasn't sure how picky FML was when checking mods' defined Minecraft version. Ending the statement with `,)` should essentially permit any version above 1.16.1, as used above with Forge's defined `versionRange="[32,)"` (I could be wrong though--I've never thoroughly worked with TOML configs before and haven't made a forge mod for about 3 years before this).

Thank you for reporting this issue. I hope you enjoy the mod, and have a wonderful day! Also, my apologies if my response is incomprehensible at times; I'm operating on 6 hours of sleep today.

**Comment by Sylladexter** [comment]
Awesome! Thanks for the mod ♥️
And don't worry, you're valid, sleep schedules be like that sometimes 😔
