### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [justinhschaaf/LlamaSteeds#6]

**Comment by justinhschaaf** [comment]
Hey, just wanted to give an update on this. I'm currently in the middle of moving, so my life is a bit hectic at the moment and my main PC setup is still sitting in a cardboard box in my new living room. Once I'm fully back up and running, I'll get working on this as soon as I can. I truly appreciate your patience and support in the meantime, thank you for playing the mod!

**Comment by venaminecraft** [comment]
Sounds great, thank you 😄

**Comment by venaminecraft** [comment]
Thank you very much!

**Comment by justinhschaaf** [comment]
Of course, happy to finally get this done! Builds are already out on CurseForge, and Modrinth ones are pending approval. A few notes about the update:

- I've gone ahead and ported the project over to Architectury, meaning it should be easier to maintain and update the mod to newer versions going forward. It doesn't require any additional dependencies on your end and made NeoForge work out of the box.

- Once Architectury updates their fork of Loom to 1.7, I'll *hopefully* be able to get a Quilt version up and running at that time as well.

- As for old Forge, it seems like there have been discussions about Architectury dropping support for it due to lack of interest and there currently isn't Forge support for 1.21, but it looks like there may still be work on it. I'm not in the Discord and I'm fairly out of the loop, so I don't know if support will be coming back at this time. I'm also unable to get Forge 1.20.5 and 1.20.6 working on both the Modrinth App and MultiMC launchers, so I have no idea what Forge's future is in the modding community. I'll keep an eye on it and see though.

**Comment by venaminecraft** [comment]
I use mainly Fabric and I don't like the forming of multiple mod loaders recently. Still each mod loader follows his principles and does good in other ways. Future is interesting.

Thanks for the detailed informations.
